#In this notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow

More specifically, we're going to cover:
* Introduction to tensors
* Getting  information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.fucntion (a way to speed up the regular Python functions)
* Using GPUs with TensorFlow (or TUPs)
* Exercises

## Introduction to Tensors

In [5]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.8.0


In [7]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [8]:
# Check the number of dimentions of a tensor (ndim stands for number of dimentions)
scalar.ndim

0

In [9]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [10]:
# Check the dimention of our vector
vector.ndim

1

In [11]:
# Create a matrix (has more than 1 dimention)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [12]:
matrix.ndim

2

In [13]:
# Create another matrix

In [15]:
another_matrix = tf.constant([[10.7, 7.],
                              [3., 2.],
                              [8., 9.]], dtype = tf.float16) # specify the data type with dtype parameter

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.7,  7. ],
       [ 3. ,  2. ],
       [ 8. ,  9. ]], dtype=float16)>

In [16]:
# Number of dimentions of another_matrix
another_matrix.ndim

2

In [20]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3],
                      [4, 5, 6]],
                     [[7, 8, 9],
                      [10, 11, 12]],
                     [[13, 14, 15],
                      [16, 17, 18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [21]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-dimentional array of numbers
* Tensor: an n-dimentional array of numbers (When n can be any number, a 0-dimentional tensor is a scalar, a 1-dimentional tensor is a vector)